### PR TITLE
Turn on hourly throttling

### PR DESCRIPTION
**Pull request by molly-moen**
Turn on hourly throttling for users and classrooms. This change does the following
- actually trigger errors and warnings for hourly usage
- stop querying and logging for daily usage limits. We can't log these anymore because they would end up blocking users, as the daily blocked users go to the same table as the hourly blocked users.
- Fix up the error keys sent back to align with those expected by Java Lab (we had `TEACHERS_BLOCKED` instead of `CLASSROOM_BLOCKED` and sent an invalid key the first time a user was blocked).
- move the teacher hourly limit to an environment variable.
NOTE: Clear the blocked users table before deploying this change

### CODE REVIEW

**Comment by bencodeorg** [comment]
Were you able to do some manual testing here?

**Review by jmkulwik — APPROVED** [review]
LGTM!

**Comment by bencodeorg** [comment]
One thing to remember is to clear the blocked_users table manually before deploying this change.

**Comment by molly-moen** [comment]
> Were you able to do some manual testing here?

@bencodeorg yes, I lowered the thresholds and checked that both users and teachers got blocked

**Comment by molly-moen** [comment]
I've cleared the blocked users table and will check again before deploying this change

**Pull request merged**
