### PR TITLE
Add a single ruby test

### PR DESCRIPTION
**Pull request by molly-moen**
This PR sets up ruby testing for `api-gateway-routes` and adds a single test. This is just to get things set up and is not meant to be full coverage of the folder yet.

This also adds the test command to the buildspec so these tests will run on commit to a PR.

## Follow-up Work
- configure unit tests for `javabuilder-authorizer`
- add more unit tests

### CODE REVIEW

**Comment by molly-moen** [comment]
the tests run in the build:
```

# Running:
.

Finished in 0.000465s, 2150.7967 runs/s, 6452.3900 assertions/s.

1 runs, 3 assertions, 0 failures, 0 errors, 0 skips
```

**Review by cat5inthecradle — APPROVED** [review]
The first test is the hardest! It's all downhill from here!

**Comment by bencodeorg** [comment]
I feel like javabuilder is like Pinocchio, on its way to becoming a real person over the past few weeks with all of this new testing and such coming together!

**Review by sanchitmalhotra126 — APPROVED** [review]
🎉

**Pull request merged**
